language: node_js
node_js:
  - 6
before_install:
  - rvm install 2.4.3
  - npm install -g npm@5
install:
  - npm install
  - bundle install
script: script/test
notifications:
  email: false
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
cache:
  bundler: true
  directories:
    - node_modules
    - test/node_modules
branches:
  only:
    - master
